---
- name: print
  hosts: "{{ host }}"
  vars:
    project_name: ""

  tasks:
    - name: print single project name
      command: echo "key is:{{ project }}"
      register: result

    - name: print stdout
      debug:
        msg: "{{ result }}"
